In [1]:
import pandas as pd
import numpy as np
import os
import glob

In [2]:
os.chdir('C:/Users/CNPL/Desktop/ANT_logs')

In [5]:
file_list = [f for f in os.listdir() if os.path.isfile(f)]
print(file_list)

['10-Flanker_A.log', '10-Flanker_B.log', '11-Flanker_A.log', '11-Flanker_B.log', '12-Flanker_A.log', '12-Flanker_B.log', '13-Flanker_A.log', '13-Flanker_B.log', '14-Flanker_A.log', '14-Flanker_B.log', '15-Flanker_A.log', '15-Flanker_B.log', '16-Flanker_A.log', '16-Flanker_B.log', '17-Flanker_A.log', '17-Flanker_B.log', '18-Flanker_A.log', '18-Flanker_B.log', '19-Flanker_A.log', '19-Flanker_B.log', '20-Flanker_A.log', '20-Flanker_B.log', '21-Flanker_A.log', '21-Flanker_B.log', '22-Flanker_A.log', '22-Flanker_B.log', '23-Flanker_A.log', '23-Flanker_B.log', '24-Flanker_A.log', '24-Flanker_B.log', '25-Flanker_A.log', '25-Flanker_B.log', '26-Flanker_A.log', '26-Flanker_B.log', '27-Flanker_A.log', '27-Flanker_B.log', '28-Flanker_A.log', '28-Flanker_B.log', '29-Flanker_A.log', '29-Flanker_B.log', '30-Flanker_A.log', '30-Flanker_B.log', '31-Flanker_A.log', '31-Flanker_B.log', '32-Flanker_A.log', '32-Flanker_B.log', '33-Flanker_A.log', '33-Flanker_B.log', '34-Flanker_A.log', '34-Flanker_B.log', '35-Flanker_A.log', '35-Flanker_B.log', '36-Flanker_A.log', '36-Flanker_B.log', '37-Flanker_A.log', '37-Flanker_B.log', '38-Flanker_A.log', '38-Flanker_B.log', '39-Flanker_A.log', '39-Flanker_B.log', '40-Flanker_A.log', '40-Flanker_B.log', '41-Flanker_A.log', '41-Flanker_B.log', '42-Flanker_A.log', '42-Flanker_B.log', '43-Flanker_A.log', '43-Flanker_B.log']

In [6]:
for filename in file_list:
    newfile = filename.replace('.log','')
    db = pd.read_csv(filename, sep = '\t', header = 2)
    db[['Code','Condition']] = db['Code'].str.split('_', expand = True)
    y = db[db['Trial'] == 'Code'].index[0]
    z = db[(db['Event Type'] == 'Pulse')].index[0]
    db = db[z:y]
    db.to_csv(f'0{newfile}.txt', sep = '\t', index = False)

In [7]:
file_list = [f for f in os.listdir() if os.path.isfile(f)]
print(file_list)

['001-Flanker_A.txt', '001-Flanker_B.txt', '002-Flanker_A.txt', '002-Flanker_B.txt', '003-Flanker_A.txt', '003-Flanker_B.txt', '004-Flanker_A.txt', '004-Flanker_B.txt', '005-Flanker_A.txt', '005-Flanker_B.txt', '006-Flanker_A.txt', '006-Flanker_B.txt', '007-Flanker_A.txt', '007-Flanker_B.txt', '008-Flanker_A.txt', '008-Flanker_B.txt', '009-Flanker_A.txt', '009-Flanker_B.txt', '010-Flanker_A.txt', '010-Flanker_B.txt', '011-Flanker_A.txt', '011-Flanker_B.txt', '012-Flanker_A.txt', '012-Flanker_B.txt', '013-Flanker_A.txt', '013-Flanker_B.txt', '014-Flanker_A.txt', '014-Flanker_B.txt', '015-Flanker_A.txt', '015-Flanker_B.txt', '016-Flanker_A.txt', '016-Flanker_B.txt', '017-Flanker_A.txt', '017-Flanker_B.txt', '018-Flanker_A.txt', '018-Flanker_B.txt', '019-Flanker_A.txt', '019-Flanker_B.txt', '020-Flanker_A.txt', '020-Flanker_B.txt', '021-Flanker_A.txt', '021-Flanker_B.txt', '022-Flanker_A.txt', '022-Flanker_B.txt', '023-Flanker_A.txt', '023-Flanker_B.txt', '024-Flanker_A.txt', '024-Flanker_B.txt', '025-Flanker_A.txt', '025-Flanker_B.txt', '026-Flanker_A.txt', '026-Flanker_B.txt', '027-Flanker_A.txt', '027-Flanker_B.txt', '028-Flanker_A.txt', '028-Flanker_B.txt', '029-Flanker_A.txt', '029-Flanker_B.txt', '030-Flanker_A.txt', '030-Flanker_B.txt', '031-Flanker_A.txt', '031-Flanker_B.txt', '032-Flanker_A.txt', '032-Flanker_B.txt', '033-Flanker_A.txt', '033-Flanker_B.txt', '034-Flanker_A.txt', '034-Flanker_B.txt', '035-Flanker_A.txt', '035-Flanker_B.txt', '036-Flanker_A.txt', '036-Flanker_B.txt', '037-Flanker_A.txt', '037-Flanker_B.txt', '038-Flanker_A.txt', '038-Flanker_B.txt', '039-Flanker_A.txt', '039-Flanker_B.txt', '040-Flanker_A.txt', '040-Flanker_B.txt', '041-Flanker_A.txt', '041-Flanker_B.txt', '042-Flanker_A.txt', '042-Flanker_B.txt', '043-Flanker_A.txt', '043-Flanker_B.txt']

In [13]:
prova = pd.read_csv(file_list[0], sep = '\t')

In [14]:
prova.head(10)

,Subject,Trial,Event Type,Code,Time,TTime,Uncertainty,Duration,Uncertainty.1,ReqTime,ReqDur,Stim Type,Pair Index,Condition
0,1,1,Pulse,44,168932,133352,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,Picture,fixationpoint,169109,133529,1,4165.0,1.0,0.0,4000.0,other,0.0,NaN
2,1,1,Picture,upcue,173274,137694,1,1166.0,1.0,4000.0,1000.0,other,0.0,NaN
3,1,1,Picture,fixationpoint,174440,138860,1,4165.0,1.0,5000.0,4000.0,other,0.0,NaN
4,1,1,Picture,RRRRRUP,178606,143026,1,17161.0,1.0,9000.0,17000.0,hit,7.0,SC
5,1,1,Response,1,184755,149175,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,1,Port Input,2,188932,153352,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,1,Pulse,44,188932,153352,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,1,Port Input,2,208932,173352,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,1,Pulse,44,208932,173352,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
prova["TimeSec"] = prova["Time"] / 10000

In [18]:
prova.loc[1,'TimeSec']

16.8932

#flanker
for filename in (file_list):
    print(filename)
    newfile = filename.replace('.txt', '')

    df = pd.read_csv(filename, sep='\t')
    #df.columns = ['Subject','Trial','EventType','Code','Time','TTime','Uncertainty','Duration','Uncertainty2','ReqTime','ReqDur','StimType','PairIndex']


    #filter = df['Subject'] != ('Picture') 
    #df_unpict = df[filter]
    #filter2 = df_unpict['Subject'] != ('Event Type')
    #df_clean = df_unpict[filter2]
    #df_final = df_clean.dropna(how = 'all')
    #df_final['Time'] = df_final['Time'].astype(float)
    df["TimeSec"] = df["Time"] / 10000
    first_pulse = df.loc[0,'TimeSec']
    df['TimePulse'] = df['TimeSec'] - first_pulse
    
    #filtro per congruent
    cong_filt = df.loc[(df['Condition'] == 'SC') | (df['Condition'] == 'NC') | (df['Condition'] == 'CC') | (df['Condition'] == 'DC')]

    cong_filt['TimePulse'].to_csv(f"{newfile}_cong.txt", header=None, index=None, sep='\n', mode='a')

    #filtro per incongruent
    incong_filt = df.loc[(df['Condition'] == 'SI') | (df['Condition'] == 'NI') | (df['Condition'] == 'CI') | (df['Condition'] == 'DI')]

    incong_filt['TimePulse'].to_csv(f"{newfile}_incong.txt", header=None, index=None, sep='\n', mode='a')

    #filtro per neutral
    neutral_filt = df.loc[(df['Condition'] == 'SN') | (df['Condition'] == 'NN') | (df['Condition'] == 'CN') | (df['Condition'] == 'DN')]

    neutral_filt['TimePulse'].to_csv(f"{newfile}_neutral.txt", header=None, index=None, sep='\n', mode='a')

In [9]:
for filename in file_list:
    newfile = filename.replace('.txt','')
    db = pd.read_csv(filename, sep = '\t')
    db['TimeSec'] = db['Time']/10000
    first_pulse = db.loc[0,'TimeSec']
    db['TimePulse'] = db['TimeSec'] - first_pulse
    filter_NC = (db['Condition'] == 'NC')
    filter_CC = (db['Condition'] == 'CC')
    filter_DC = (db['Condition'] == 'DC')
    filter_SC = (db['Condition'] == 'SC')
    filter_NI = (db['Condition'] == 'NI')
    filter_CI = (db['Condition'] == 'CI')
    filter_DI = (db['Condition'] == 'DI')
    filter_SI = (db['Condition'] == 'SI')
    filter_NN = (db['Condition'] == 'NN')
    filter_CN = (db['Condition'] == 'CN')
    filter_DN = (db['Condition'] == 'DN')
    filter_SN = (db['Condition'] == 'SN')
    
    filters = [(filter_NC,'NC'),(filter_CC,'CC'),(filter_DC,'DC'),(filter_SC,'SC'),(filter_NI,'NI'),(filter_CI,'CI'),(filter_DI,'DI'),(filter_SI,'SI'),(filter_NN,'NN'),(filter_CN,'CN'),(filter_DN,'DN'),(filter_SN,'SN')]

    
    for x,n in (filters):
        db_filt = db.loc[x]
        db_filt = db_filt['TimePulse']
        db_filt.to_csv(f"{newfile}_{n}.txt", index = False, header = False)